### ISSUE TITLE
Algorithm Development

### ISSUE THREAD

**Issue by brio50** [brio50/divisor#3]
## In React (Javascript):
- [x] unit conversion: `mm` to `in`, `in` to `ft`
    * `mm2in()`
    * `in2ft()`
- [ ] assuming the value in `7.125` inch rounded to nearest `divisor` of an `in`
    * analytically: `floor(7.125) +  ceil(0.125*divsor)/divisor "in"`
    * interpolation: `x=0:divisor:1; i=interp1(x,0.125,'ceil'); y=x(i);` 
- [ ]  assuming the value in `7.125` ft rounded to nearest `ft` + `divisor` of an `in`
    * analytically: `floor(7.125) "ft" + ceil(ft2in(0.125)*divsor)/divisor "in"`
    
## In Python:
~~- [Two routes, one for each method to learn differences between dynamic `ON-EVENT` and `PUT`/`GET` static~~

**Comment by anmol111pal** [comment]
Hey @brio50 , may I review the changes/enhancements to this.
Please assign this to me.

**Comment by brio50** [comment]
I enabled interaction limits through [Moderator Options](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository) for 6 months. I do not want external influences as I'd like to [build my skills](https://github.com/brio50/divisor/blob/main/README.md#motivation) first.

**Comment by brio50** [comment]
## React Familiarization
* https://react.dev/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page
    * [`createRoot()`](https://react.dev/reference/react-dom/client/createRoot#rendering-a-page-partially-built-with-react)

**Comment by brio50** [comment]
## Task 1 Completed [`v0.1.0`]
* https://github.com/brio50/divisor/commit/cf302f034b6cbf97d1f24278f339e08631ac31d2#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67
